### ISSUE TITLE
Wrong PURLS in PCO (https)

### ISSUE THREAD

**Issue by matentzn** [PopulationAndCommunityOntology/pco#100] opened 2020-12-16 11:22 UTC
https://purl.obolibrary.org/obo/PCO_0000040
https://purl.obolibrary.org/obo/PCO_0000041
https://purl.obolibrary.org/obo/PCO_0000042
https://purl.obolibrary.org/obo/PCO_0000043
https://purl.obolibrary.org/obo/PCO_0000044
https://purl.obolibrary.org/obo/PCO_0000045
https://purl.obolibrary.org/obo/PCO_0000046

An example of a correct IRI is (no https!):
http://purl.obolibrary.org/obo/ENVO_01000549

Context:
https://github.com/orgs/OBOFoundry/projects/5

**Comment by cmungall** [comment] 2020-12-19 01:28
I think this is a dupe of #85 - I believe these were all fixed @ramonawalls  - maybe just need a new release?

**Comment by ramonawalls** [comment] 2021-04-21 01:43
Yes. They have been fixed in #85

**Closed as completed by ramonawalls** 2021-04-21 01:43 UTC
